language: go
arch:
    - amd64
    - ppc64le
go_import_path: go.opencensus.io

go:
  - 1.13.x

env:
  global:
    GO111MODULE=on

before_script:
  - make install-tools

script:
  - make travis-ci
  - go run internal/check/version.go # TODO move this to makefile
